@startuml
'https://plantuml.com/activity-diagram-beta

title ClientSide\n

start
:connect();

if (choice 1) then (signup)
  :signup;
  repeat
    :EnterUserName();
  repeat while (unique Name?) is (no)
        ->yes;
  repeat
    :EnterPassword();
  repeat while (Strong Password?) is (no)
        ->yes;
  :signupDone;
  stop
elseif(choice 2) then (login)
    :Login;
      repeat
        :EnterUserName();
        :EnterPassword();
      repeat while (authenticatedUser?) is (no)
         ->yes;
      :LoginDone;
      repeat : Loop;
      if (Manager) then (true)
        if(viewData)
        elseif(putData)
        elseif(OthersData)
        else (Exit)
        endif
      else (false)
        if(viewData)
        elseif(putData)
        elseif(UpgradeRole)
        else(Exit)
        endif
      endif
      repeat while(GoOn?) is (yes)
      ->no;
    stop
elseif(choice 3) then (exit)
    stop
else (Wrong choice)
endif
stop

@enduml
